package com.example.backend.core.enums;

public enum NotificationEvent {
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_COMPLETED,
    BOOKING_REMINDER,
    OWNER_NEW_BOOKING,
    OWNER_BOOKING_CANCELLED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_EXPIRED,
    ADMIN_NEW_USER,
    ADMIN_PAYMENT_ALERT
}
