spring.application.name=BS68

# Render port
server.port=${PORT:8080}

# PostgreSQL - Render
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d7ehbkfaqgkc7383dk00-a:5432/bs68}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.clean-disabled=true
spring.flyway.out-of-order=true

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File upload
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Firebase config path
firebase.config.path=${FIREBASE_CONFIG_PATH:firebase-service-account.json}

# OTP expiry
otp.expiry-minutes=5

# VNPay
payment.vnpay.pay-url=${VNPAY_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
payment.vnpay.frontend-result-url=${VNPAY_FRONTEND_RESULT_URL:https://bs86-1.onrender.com/payment-result}
payment.vnpay.return-url=${payment.vnpay.frontend-result-url}
payment.vnpay.tmn-code=${VNPAY_TMN_CODE}
payment.vnpay.secret-key=${VNPAY_SECRET_KEY}

payment.hold-timeout-minutes=10
notification.email.enabled=false
notification.reminder.minutes-before=30
notification.reminder.fixed-delay-ms=60000
